export const DISHES = [
  {
    id: 'doro-wat',
    name: 'Doro Wat (Traditional Chicken Stew)',
    amharicName: 'ዶሮ ወጥ',
    category: 'Signature',
    price: 450,
    priceFormatted: '450 ETB',
    spiceLevel: 'Spicy 🌶️🌶️🌶️',
    isFasting: false,
    rating: 4.9,
    prepTime: '25 min',
    description: 'The iconic Ethiopian national dish. Tender chicken leg slow-simmered in a rich, berbere-infused onion gravy, accompanied by hard-boiled eggs infused with spice.',
    ingredients: ['Free-range Chicken', 'Berbere Spice', 'Niter Kibbeh (Spiced Butter)', 'Hard-boiled Eggs', 'Red Onions', 'Garlic & Ginger', 'Injera'],
    image: '🍗',
    popular: true,
  },
  {
    id: 'kitfo',
    name: 'Special Kitfo',
    amharicName: 'ክትፎ',
    category: 'Signature',
    price: 480,
    priceFormatted: '480 ETB',
    spiceLevel: 'Medium-Spicy 🌶️🌶️',
    isFasting: false,
    rating: 4.95,
    prepTime: '15 min',
    description: 'Freshly minced prime lean beef warmed with infused niter kibbeh (clarified spiced butter) and authentic mitmita spice. Served with house-made ayib (cottage cheese) and gomen.',
    ingredients: ['Prime Lean Beef', 'Mitmita Spice', 'Niter Kibbeh', 'Ayib (Cheese)', 'Collard Greens', 'Kocho / Injera'],
    image: '🥩',
    popular: true,
  },
  {
    id: 'beyaynetu',
    name: 'Yetsom Beyaynetu (Veggie Combo)',
    amharicName: 'የጾም በያይነቱ',
    category: 'Fasting / Veggie',
    price: 320,
    priceFormatted: '320 ETB',
    spiceLevel: 'Mild to Medium 🌶️',
    isFasting: true,
    rating: 4.85,
    prepTime: '10 min',
    description: 'A vibrant, colorful feast of vegan dishes arranged on soft teff injera. Features Shiro, Misir Wat (red lentils), Kik Alicha (yellow split peas), Gomen, and Beet salad.',
    ingredients: ['Misir Wat (Spicy Lentils)', 'Kik Alicha (Yellow Peas)', 'Shiro', 'Gomen (Collards)', 'Key Sir (Beetroot)', 'Fasolia (Green Beans)', 'Teff Injera'],
    image: '🥗',
    popular: true,
  },
  {
    id: 'shiro',
    name: 'Shiro Tegabere',
    amharicName: 'ሽሮ ተጋቢኖ',
    category: 'Fasting / Veggie',
    price: 260,
    priceFormatted: '260 ETB',
    spiceLevel: 'Medium 🌶️🌶️',
    isFasting: true,
    rating: 4.75,
    prepTime: '15 min',
    description: 'Velvety, rich chickpea flour stew seasoned with berbere, garlic, and sacred spices, served bubbling hot in a clay vessel (ebet/denesh).',
    ingredients: ['Sun-dried Chickpea Flour', 'Berbere', 'Garlic & Shallots', 'Vegetable Oil', 'Fresh Jalapeño', 'Injera'],
    image: '🍲',
    popular: false,
  },
  {
    id: 'special-tibs',
    name: 'Special Beef Tibs',
    amharicName: 'ስፔሻል ጥብስ',
    category: 'Tibs',
    price: 420,
    priceFormatted: '420 ETB',
    spiceLevel: 'Medium 🌶️🌶️',
    isFasting: false,
    rating: 4.88,
    prepTime: '20 min',
    description: 'Tender tenderloin beef cubes flash-sautéed in a hot pan with sliced onions, fresh rosemary sprigs, green jalapeños, and aromatic kibbeh.',
    ingredients: ['Beef Tenderloin', 'Fresh Rosemary', 'Green Jalapeño', 'Onions', 'Niter Kibbeh', 'Garlic', 'Teff Injera'],
    image: '🥘',
    popular: true,
  },
  {
    id: 'gomen-besiga',
    name: 'Gomen Be Siga',
    amharicName: 'ጎመን በሥጋ',
    category: 'Signature',
    price: 380,
    priceFormatted: '380 ETB',
    spiceLevel: 'Mild 🌶️',
    isFasting: false,
    rating: 4.7,
    prepTime: '20 min',
    description: 'Finely chopped collard greens stewed with bone-in beef chunks, garlic, ginger, and spiced butter, creating a comforting savory dish.',
    ingredients: ['Fresh Collard Greens', 'Beef Chunks', 'Garlic & Ginger', 'Niter Kibbeh', 'Cardamom', 'Injera'],
    image: '🥬',
    popular: false,
  }
];

export function getAllDishes() {
  return DISHES;
}

export function getDishById(id) {
  return DISHES.find((d) => d.id === id);
}

export function getCategories() {
  return ['All', 'Signature', 'Fasting / Veggie', 'Tibs'];
}
